# Generated by Django 5.2.6 on 2026-02-04 09:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_city_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('posting_ref', models.CharField(db_index=True, help_text='Auto-generated posting reference (e.g., LRP20260204143022ABC123)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total repayment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated principal portion (set on approval)', max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated interest portion (set on approval)', max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('direct_debit', 'Direct Debit')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference, receipt number, etc.', max_length=100)),
                ('payment_details', models.TextField(blank=True, help_text='Additional payment information (bank name, mobile number, etc.)')),
                ('payment_date', models.DateField(help_text='Date the payment was received')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes from staff member submitting the repayment')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer (approval/rejection reason)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_postings', to='core.branch')),
                ('client', models.ForeignKey(help_text='Client making the repayment', on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_postings', to='core.client')),
                ('loan', models.ForeignKey(help_text='Loan being repaid', on_delete=django.db.models.deletion.PROTECT, related_name='repayment_postings', to='core.loan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_repayments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_loan_repayments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction created when this posting was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_posting', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Loan Repayment Posting',
                'verbose_name_plural': 'Loan Repayment Postings',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'branch'], name='core_loanre_status_389cee_idx'), models.Index(fields=['loan', 'status'], name='core_loanre_loan_id_91927b_idx'), models.Index(fields=['submitted_at'], name='core_loanre_submitt_7e2126_idx'), models.Index(fields=['payment_date'], name='core_loanre_payment_093a8c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_repayment_posting_amount_positive')],
            },
        ),
    ]
