# Generated by Django 5.2.6 on 2026-02-05 07:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loanrepaymentposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsDepositPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('posting_ref', models.CharField(db_index=True, help_text='Auto-generated posting reference (e.g., SDP20260205143022ABC123)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deposit amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('direct_debit', 'Direct Debit')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference, receipt number, etc.', max_length=100)),
                ('payment_details', models.TextField(blank=True, help_text='Additional payment information')),
                ('payment_date', models.DateField(help_text='Date the payment was received')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes from staff member submitting the deposit')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer (approval/rejection reason)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_deposit_postings', to='core.branch')),
                ('client', models.ForeignKey(help_text='Client making the deposit', on_delete=django.db.models.deletion.PROTECT, related_name='savings_deposit_postings', to='core.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_savings_deposits', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(help_text='Savings account receiving deposit', on_delete=django.db.models.deletion.PROTECT, related_name='deposit_postings', to='core.savingsaccount')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_savings_deposits', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction created when this posting was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_posting', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Savings Deposit Posting',
                'verbose_name_plural': 'Savings Deposit Postings',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'branch'], name='core_saving_status_fbaf2e_idx'), models.Index(fields=['savings_account', 'status'], name='core_saving_savings_579175_idx'), models.Index(fields=['submitted_at'], name='core_saving_submitt_7a94e8_idx'), models.Index(fields=['payment_date'], name='core_saving_payment_a2485c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='savings_deposit_posting_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='SavingsWithdrawalPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('posting_ref', models.CharField(db_index=True, help_text='Auto-generated posting reference (e.g., SWP20260205143022ABC123)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty amount for early withdrawal (calculated on approval)', max_digits=15)),
                ('is_early_withdrawal', models.BooleanField(default=False, help_text='Is this an early withdrawal from fixed deposit?')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference, receipt number, etc.', max_length=100)),
                ('payment_details', models.TextField(blank=True, help_text='Additional payment information')),
                ('withdrawal_date', models.DateField(help_text='Date of withdrawal')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes from staff member submitting the withdrawal')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer (approval/rejection reason)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_withdrawal_postings', to='core.branch')),
                ('client', models.ForeignKey(help_text='Client making the withdrawal', on_delete=django.db.models.deletion.PROTECT, related_name='savings_withdrawal_postings', to='core.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_savings_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(help_text='Savings account for withdrawal', on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_postings', to='core.savingsaccount')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_savings_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction created when this posting was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_posting', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Savings Withdrawal Posting',
                'verbose_name_plural': 'Savings Withdrawal Postings',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'branch'], name='core_saving_status_af5e05_idx'), models.Index(fields=['savings_account', 'status'], name='core_saving_savings_e20c8c_idx'), models.Index(fields=['submitted_at'], name='core_saving_submitt_7ea347_idx'), models.Index(fields=['withdrawal_date'], name='core_saving_withdra_8ec82d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='savings_withdrawal_posting_amount_positive')],
            },
        ),
    ]
