# Generated by Django 5.2.6 on 2026-02-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_savings_transaction_posting_models'),
    ]

    operations = [
        # Remove the problematic unique_together constraint that includes 'status'
        # This was preventing clients from being re-approved if they left and rejoined
        migrations.AlterUniqueTogether(
            name='groupmembershiprequest',
            unique_together=set(),
        ),
    ]
