# Generated by Django 5.2.6 on 2026-02-22 00:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loan_accrued_interest_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('automatic', 'System Generated'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('fee_collection', 'Fee Collection'), ('reversal', 'Reversal Entry'), ('adjustment', 'Adjustment Entry'), ('insurance_payout', 'Insurance Payout'), ('interbranch_transfer', 'Inter-Branch Transfer')], max_length=30),
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('recon_ref', models.CharField(db_index=True, help_text='Auto-generated reference, e.g. RECON-20250101-1010', max_length=50, unique=True)),
                ('period_start', models.DateField(help_text='Start of the reconciliation period')),
                ('period_end', models.DateField(help_text='End of the reconciliation period')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GL balance at period_start', max_digits=15)),
                ('bank_statement_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Closing balance per bank statement', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(help_text='GL account being reconciled (e.g. 1010, 1020)', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('claim_ref', models.CharField(db_index=True, help_text='Auto-generated, e.g. CLAIM-LN2025001-001', max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('death', 'Death of Borrower'), ('disability', 'Permanent Disability'), ('fire', 'Fire / Property Damage'), ('theft', 'Theft / Burglary'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], max_length=30)),
                ('event_date', models.DateField(help_text='Date the insured event occurred')),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Amount being claimed (defaults to loan outstanding balance)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual payout received from insurer', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid Out')], db_index=True, default='submitted', max_length=20)),
                ('description', models.TextField(help_text='Details about the insured event')),
                ('document_references', models.TextField(blank=True, help_text='Notes about supporting documents submitted')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims_filed', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='core.loan')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims_paid', to=settings.AUTH_USER_MODEL)),
                ('payout_journal', models.ForeignKey(blank=True, help_text='Journal entry posted when payout is recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_payouts', to='core.journalentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Insurance Claim',
                'verbose_name_plural': 'Loan Insurance Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('line_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money leaving the bank account', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money entering the bank account', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('disputed', 'Disputed')], db_index=True, default='unmatched', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('matched_gl_line', models.ForeignKey(blank=True, help_text='Matched GL journal line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_matches', to='core.journalentryline')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.bankreconciliation')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['line_date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('matched_gl_line__isnull', False)), fields=('matched_gl_line',), name='unique_gl_line_match')],
            },
        ),
        migrations.CreateModel(
            name='InterBranchTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('transfer_ref', models.CharField(db_index=True, help_text='Auto-generated, e.g. TRF-20250101-001', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('purpose', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved — In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Person confirming receipt at destination branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_completed', to=settings.AUTH_USER_MODEL)),
                ('destination_journal', models.ForeignKey(blank=True, help_text='Journal posted at destination branch on completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_destination', to='core.journalentry')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='core.branch')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('source_journal', models.ForeignKey(blank=True, help_text='Journal posted at source branch on approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_source', to='core.journalentry')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.branch')),
            ],
            options={
                'verbose_name': 'Inter-Branch Transfer',
                'verbose_name_plural': 'Inter-Branch Transfers',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.00'))), name='transfer_amount_positive')],
            },
        ),
    ]
