# Generated by Django 5.2.6 on 2026-02-23 09:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_journalentry_entry_type_bankreconciliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='id_card_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Back of the guarantor's ID card", max_length=255, null=True, verbose_name='id_card_back'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='id_card_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Front of the guarantor's ID card", max_length=255, null=True, verbose_name='id_card_front'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Guarantor's signature image", max_length=255, null=True, verbose_name='signature'),
        ),
    ]
