# Generated by Django 5.2.6 on 2026-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_guarantor_id_card_back_guarantor_id_card_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client_registered', 'New Client Registered'), ('client_approved', 'Client Approved'), ('loan_applied', 'Loan Application Submitted'), ('loan_fees_paid', 'Loan Fees Paid'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('loan_overdue', 'Loan Overdue'), ('loan_completed', 'Loan Completed'), ('savings_created', 'Savings Account Created'), ('savings_approved', 'Savings Account Approved'), ('deposit_made', 'Deposit Made'), ('withdrawal_made', 'Withdrawal Made'), ('deposit_pending', 'Deposit Pending Approval'), ('withdrawal_pending', 'Withdrawal Pending Approval'), ('transaction_approved', 'Transaction Approved'), ('transaction_rejected', 'Transaction Rejected'), ('staff_created', 'Staff Account Created'), ('group_created', 'Group Created'), ('system_alert', 'System Alert'), ('assignment_request_pending', 'Assignment Request Pending'), ('assignment_request_approved', 'Assignment Request Approved'), ('assignment_request_rejected', 'Assignment Request Rejected'), ('branch_changed', 'Branch Assignment Updated'), ('group_assigned', 'Group Assignment Updated'), ('group_removed', 'Removed from Group'), ('group_unassigned', 'Group Unassigned from Staff'), ('client_unassigned', 'Client Unassigned'), ('clients_assigned', 'Multiple Clients Assigned'), ('savings_maturity', 'Fixed Deposit Maturing'), ('loan_penalty_applied', 'Automatic Penalty Applied')], db_index=True, max_length=50),
        ),
    ]
