# Generated by Django 5.2.6 on 2026-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loanproduct_add_repayment_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='How often borrowers make installment payments (does not affect interest calculation)', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client_registered', 'New Client Registered'), ('client_approved', 'Client Approved'), ('loan_applied', 'Loan Application Submitted'), ('repayment_posted', 'Repayment Pending Approval'), ('loan_fees_paid', 'Loan Fees Paid'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('loan_overdue', 'Loan Overdue'), ('loan_completed', 'Loan Completed'), ('savings_created', 'Savings Account Created'), ('savings_approved', 'Savings Account Approved'), ('deposit_made', 'Deposit Made'), ('withdrawal_made', 'Withdrawal Made'), ('deposit_pending', 'Deposit Pending Approval'), ('withdrawal_pending', 'Withdrawal Pending Approval'), ('transaction_approved', 'Transaction Approved'), ('transaction_rejected', 'Transaction Rejected'), ('staff_created', 'Staff Account Created'), ('group_created', 'Group Created'), ('system_alert', 'System Alert'), ('assignment_request_pending', 'Assignment Request Pending'), ('assignment_request_approved', 'Assignment Request Approved'), ('assignment_request_rejected', 'Assignment Request Rejected'), ('branch_changed', 'Branch Assignment Updated'), ('group_assigned', 'Group Assignment Updated'), ('group_removed', 'Removed from Group'), ('group_unassigned', 'Group Unassigned from Staff'), ('client_unassigned', 'Client Unassigned'), ('clients_assigned', 'Multiple Clients Assigned'), ('savings_maturity', 'Fixed Deposit Maturing'), ('loan_penalty_applied', 'Automatic Penalty Applied'), ('transfer_requested', 'Transfer Requested'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('transfer_completed', 'Transfer Completed'), ('insurance_claim_filed', 'Insurance Claim Filed'), ('insurance_claim_approved', 'Insurance Claim Approved'), ('insurance_claim_rejected', 'Insurance Claim Rejected'), ('insurance_claim_paid', 'Insurance Claim Paid')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Savings Deposit'), ('withdrawal', 'Savings Withdrawal'), ('interest_credit', 'Interest Credit'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('interest_applied', 'Interest Applied'), ('charges_at_disbursement', 'Charges At Disbursement'), ('registration_fee', 'Client Registration Fee'), ('id_card_fee', 'ID Card Fee'), ('membership_card_fee', 'Membership Card Fee'), ('loan_insurance_fee', 'Loan Insurance Fee'), ('loan_form_fee', 'Loan Form Fee'), ('risk_premium', 'Risk Premium Fee'), ('rp_income', 'RP Income Fee'), ('tech_fee', 'Technology Fee'), ('fee', 'Fee / Charge'), ('reversal', 'Reversal'), ('transfer', 'Transfer')], db_index=True, max_length=30),
        ),
    ]
