# Generated by Django 5.2.6 on 2026-02-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='loan_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role__in': ['staff', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_client_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
