"""
Django settings for seashore project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import warnings


from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Suppress naive datetime warnings for existing database records
# All new code uses timezone-aware datetimes (timezone.now())
warnings.filterwarnings(
    'ignore',
    message='DateTimeField .* received a naive datetime',
    category=RuntimeWarning,
    module='django.db.models.fields'
)

import os

import cloudinary
import cloudinary.uploader
import cloudinary.api
import dj_database_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)


ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [h.strip() for h in v.split(",") if h.strip()],
)


cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME', default='your-cloud-name'),
    api_key = config('CLOUDINARY_API_KEY', default='your-api-key'),
    api_secret = config('CLOUDINARY_API_SECRET', default='your-api-secret'),
    secure = True
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default='your-cloud-name'),
    'API_KEY': config('CLOUDINARY_API_KEY', default='your-api-key'),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default='your-api-secret'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Africa's Talking SMS
AT_USERNAME  = config('AT_USERNAME',  default='sandbox')
AT_API_KEY   = config('AT_API_KEY',   default='')
AT_SENDER_ID = config('AT_SENDER_ID', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize',

    # Third party apps
    'cloudinary_storage',
    'cloudinary',
    'auditlog',
    'django_celery_beat',
    'django_celery_results',
    'axes',

    # REST API
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',

    'core',
]

# Custom User Model
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',               # must be after AuthenticationMiddleware
    'core.middleware.IPSessionLockMiddleware',      # terminates sessions on IP change
    'auditlog.middleware.AuditlogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'seashore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'seashore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True



LOGIN_URL = "core:login"
LOGIN_OUT = "core:logout"



# For Email (Development/Testing)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_SSL = True  # ✅ CORRECT for port 465
EMAIL_USE_TLS = False  # ✅ Must be False when using SSL
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='your-email@gmail.com')  # Your Email
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='your-app-password')  # Email App Password
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Citadel Markets Pro <support@citadelmarketspro.com>')
ADMIN_NOTIFICATION_EMAIL = config('ADMIN_NOTIFICATION_EMAIL', default='support@citadelmarketspro.com')




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIR = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# Authentication Backends
# =============================================================================
AUTHENTICATION_BACKENDS = [
    # django-axes must be first so lockouts are checked before authentication
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# =============================================================================
# django-axes — Login Throttling / Brute Force Protection
# =============================================================================
from datetime import timedelta as _timedelta  # noqa: E402

AXES_FAILURE_LIMIT          = 5                          # lock after 5 failed attempts
AXES_COOLOFF_TIME           = _timedelta(hours=1)        # unlock automatically after 1 hour
AXES_LOCK_OUT_AT_FAILURE    = True
AXES_RESET_ON_SUCCESS       = True                       # reset counter on successful login
AXES_LOCKOUT_PARAMETERS     = ['username', 'ip_address'] # lock per username+IP combination
AXES_ENABLE_ACCESS_FAILURE_LOG = True                    # log every failure to DB
AXES_LOCKOUT_URL            = '/login/'                  # axes appends ?username=... so don't add our own ?params
AXES_HTTP_RESPONSE_CODE     = 403


# =============================================================================
# Celery Configuration
# =============================================================================
import ssl as _ssl  # noqa: E402
from celery.schedules import crontab  # noqa: E402

REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

CELERY_BROKER_URL            = REDIS_URL
# Suppress "no ssl options" warnings when using rediss:// with Upstash
CELERY_BROKER_USE_SSL        = {'ssl_cert_reqs': _ssl.CERT_NONE}
CELERY_RESULT_BACKEND        = 'django-db'          # Store task results in Django DB
CELERY_CACHE_BACKEND         = 'django-cache'
CELERY_TASK_SERIALIZER       = 'json'
CELERY_RESULT_SERIALIZER     = 'json'
CELERY_ACCEPT_CONTENT        = ['json']
CELERY_TIMEZONE              = 'Africa/Lagos'
CELERY_ENABLE_UTC            = True
CELERY_TASK_TRACK_STARTED    = True
CELERY_TASK_SOFT_TIME_LIMIT  = 300   # 5 min soft limit
CELERY_TASK_TIME_LIMIT       = 360   # 6 min hard limit

# Use django-celery-beat for periodic task storage (schedules live in the DB,
# editable from the Django admin without restarting workers)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Default beat schedule — tasks are also manageable from Django admin
CELERY_BEAT_SCHEDULE = {
    # ── Loan tasks ──────────────────────────────────────────────────────────
    'detect-overdue-loans-daily': {
        'task':     'core.tasks.loan_tasks.detect_overdue_loans',
        'schedule': crontab(hour=1, minute=0),        # 01:00 WAT daily
    },
    'recalculate-par-daily': {
        'task':     'core.tasks.loan_tasks.recalculate_par',
        'schedule': crontab(hour=1, minute=30),       # 01:30 WAT daily
    },
    'accrue-loan-interest-monthly': {
        'task':     'core.tasks.loan_tasks.accrue_monthly_loan_interest',
        'schedule': crontab(hour=2, minute=30, day_of_month=1),  # 1st of month 02:30 WAT
    },
    # ── Savings tasks ────────────────────────────────────────────────────────
    'post-savings-interest-monthly': {
        'task':     'core.tasks.savings_tasks.post_savings_interest',
        'schedule': crontab(hour=2, minute=0, day_of_month=1),   # 1st of month 02:00 WAT
    },
    'alert-fd-maturities-daily': {
        'task':     'core.tasks.savings_tasks.alert_fixed_deposit_maturities',
        'schedule': crontab(hour=8, minute=0),        # 08:00 WAT daily
    },
    # ── Report / email tasks ─────────────────────────────────────────────────
    'email-daily-par-digest': {
        'task':     'core.tasks.report_tasks.email_daily_par_digest',
        'schedule': crontab(hour=7, minute=0),        # 07:00 WAT daily
    },
    'email-monthly-summary': {
        'task':     'core.tasks.report_tasks.email_monthly_summary',
        'schedule': crontab(hour=6, minute=0, day_of_month=1),  # 1st of month 06:00 WAT
    },
    # ── SMS tasks (Africa's Talking) ─────────────────────────────────────────
    'sms-repayment-reminders': {
        'task':     'core.tasks.sms_tasks.send_repayment_reminders',
        'schedule': crontab(hour=8, minute=0),   # 08:00 WAT daily
    },
    'sms-overdue-alerts': {
        'task':     'core.tasks.sms_tasks.send_overdue_alerts',
        'schedule': crontab(hour=9, minute=0),   # 09:00 WAT daily
    },
}

# =============================================================================
# Django REST Framework
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '300/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Seashore Microfinance API',
    'DESCRIPTION': (
        'REST API for the Seashore Microfinance Information System. '
        'Authenticate with a Token header: Authorization: Token <token>'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'auth',     'description': 'Token authentication'},
        {'name': 'clients',  'description': 'Client management'},
        {'name': 'loans',    'description': 'Loan lifecycle'},
        {'name': 'savings',  'description': 'Savings accounts'},
        {'name': 'reports',  'description': 'Portfolio & financial reports'},
    ],
}

# =============================================================================
# Production Security Settings
# (All are keyed off DEBUG so development is unaffected)
# =============================================================================

if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT          = True
    SECURE_PROXY_SSL_HEADER      = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS — tell browsers to always use HTTPS for 1 year
    SECURE_HSTS_SECONDS          = 31536000   # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD          = True

    # Prevent browsers from MIME-sniffing the content type
    SECURE_CONTENT_TYPE_NOSNIFF  = True

    # Enable XSS filter in older browsers
    SECURE_BROWSER_XSS_FILTER    = True

    # Cookies only sent over HTTPS and inaccessible to JS
    SESSION_COOKIE_SECURE        = True
    SESSION_COOKIE_HTTPONLY      = True
    SESSION_COOKIE_SAMESITE      = 'Lax'

    CSRF_COOKIE_SECURE           = True
    CSRF_COOKIE_HTTPONLY         = True
    CSRF_COOKIE_SAMESITE         = 'Lax'

    # Deny framing entirely (clickjacking protection)
    X_FRAME_OPTIONS              = 'DENY'

    # Session lifetime — expire after 8 hours of inactivity
    SESSION_COOKIE_AGE           = 28800          # 8 hours in seconds
    SESSION_SAVE_EVERY_REQUEST   = True           # slide the expiry on each request
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False
